version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g mocha
      - npm install -g serverless
      - serverless deploy | tee deploy.out
      - . ./endpoint.sh
      - npm test
